src/synonym.rs

"Entries" has changed to "Iter" in the most recent Rust master branch.

Change 'Entries' to 'Iter' due to updated HashMap API in Rust master.

---

src/lib.rs
src/synonym.rs

Various fixes for `Iterator` (breaking change [here](https://github.com/rust-lang/rust/commit/c6c786671d692d7b13c2e5c68a53001327b4b125)).
This PR, when merged with #71, compiles and tests just fine (of course, with some warnings).

Update to rust master

---

src/parse.rs

The hashmap API seems to have changed slightly in the latest nightly.
See commit: rust-lang/rust@400c3a0d for details.
This patch makes the following adjustments:
* `VacantEntry#set()` -> `VacantEntry#insert()`
* `HashMap#entry()` now takes keys by reference.

Fixes for some changes to the HashMap API

---

docopt_macros/examples/add.rs
docopt_macros/examples/cp.rs
docopt_macros/examples/macro.rs
docopt_macros/examples/rustc.rs
examples/cargo.rs
examples/cp.rs
examples/decode.rs
examples/hashmap.rs
examples/verbose_multiple.rs
src/lib.rs
src/parse.rs
src/synonym.rs
src/test/mod.rs
src/wordlist.rs

I have outlined the changes in the commit message.
`#![allow(unstable)]` is required because for some reason the documentation test runner sets `#![deny(unstable)]`.

Update for Rustup

---

docopt_macros/examples/cp.rs
docopt_macros/examples/macro.rs
docopt_macros/examples/rustc.rs
examples/cargo.rs
examples/cp.rs
examples/decode.rs
examples/verbose_multiple.rs
src/lib.rs
src/parse.rs
src/synonym.rs
src/wordlist.rs

This commit replaces usage of the `Show` and `fmt::String` traits with the `Debug` and `Display` traits, respectively. This was required to fix breaking changes introduced by rust-lang/rust#21457. Additionally, the superfluous `detail` method on `docopt::Error` was removed as it no longer exists in the trait. Also, hi!

Update Show/String to Debug/Display

---

src/lib.rs
src/wordlist.rs

Update references to `std::io` with `std::old_io` due to rust-lang/rust#21543.

Replace io with old_io

---

README.md

Bring the readme in line with the actual usage.

Fix extern crate references to rustc-serialize

---

src/parse.rs
src/test/mod.rs
src/test/suggestions.rs

Initial implementation of suggestions for unknown flags.
Given `Usage: testing [--release]`, docopt will behave like this:
```
$ testing --rlease
Unknown flag: '--rlease'. Did you mean '--release'?
Usage: testing [--release]
```
Closes #98

Add initial implementation of suggestions

---

Cargo.toml
src/lib.rs
src/parse.rs
src/wordlist.rs

Use a Levenshtein distance implementation from the strsim crate

---

docopt_macros/src/macro.rs

See https://github.com/rust-lang/rust/pull/27234

Update for recent changes in libsyntax

---

docopt_macros/src/macro.rs

Came from  from rust-lang/rust#29285.  Looks like it broke a few days ago.

Use new parse_..._panic functions

---

examples/cargo.rs

Enable  passing option to a subcommand, like `cargo build -h`.

Use options_first(true) in cargo example

---

docopt_macros/src/macro.rs

The return type of `Parser::eat()` and a few other methods is no longer wrapped in a `Result`.
See rust-lang/rust@9023c659af8a43dd5e284d7b311e5f19721c9bd8 for the
changes in libsyntax.

Update for simplified parser API.

---

src/parse.rs

For example, calling `cargo build --release=yes` would print:
Flag '--release' cannot have an argument, but found 'Some("yes")'.
With this patch, only `... but found 'yes'.` is printed.

Do not leak Rust details into user errors

---

docopt_macros/src/macro.rs

Without this change `parse_seq_to_end` eats the EOF so `expect(Eof)` ICEs under rust-lang/rust#32479.

Use parse_seq_to_before_end to keep the end token.

---

docopt_macros/src/macro.rs

This fixes the build for `docopt_macros` for `nightly-2016-04-27` (and maybe earlier versions)

Switch to P::new instead of P::empty

---

src/parse.rs
src/test/testcases.docopt
src/test/testcases.rs

This fixes docopt/docopt.rs#187.
I solved the issue by allowing a regex to find a longest matching substring.
Because we don't expect another `']'` after a default value notation "[default: blahblah]", we can simply consider a last`']'` is the closing bracket of the notation.  So, finding the longest matching works here.
I also found that [docopt.py uses the same regex](https://github.com/docopt/docopt/blob/master/docopt.py#L161).

Fix parsing default values containing ']'

---

src/parse.rs
src/test/mod.rs

This should fix the performance issues noted in #195.
I have added special cases for handling `[--flag...]`, `--flag...`, `[--flag]...` and a test case for the issue. There is some code duplication in the fix currently.
---
By the way, I would have use the following cleaner code instead of
nested match if box syntax was in stable:
&Repeat(box PatAtom(ref a @ Short(_)))
| &Repeat(box PatAtom(ref a @ Long(_))) => {
let argv_count = self.argv.counts.get(a)
.map_or(0, |&x| x);
let max_count = base.max_counts.get(a)
.map_or(0, |&x| x);
if argv_count > max_count {
for _ in max_count..argv_count {
base.use_optional_flag(a);
}
}
}

Fix issue #195

---

docopt_macros/src/macro.rs

What's the project policy for tracking nightly? These changes seem to make it work with my nightly:
```
% rustc --version
rustc 1.15.0-nightly (3bf2be9ce 2016-11-22)
```

update for rust nightly

---

.travis.yml
Cargo.toml
README.md
docopt_macros/Cargo.toml
docopt_macros/examples/add.rs
docopt_macros/examples/cp.rs
docopt_macros/examples/macro.rs
docopt_macros/examples/rustc.rs
docopt_macros/src/macro.rs
examples/cargo.rs
examples/cp.rs
examples/decode.rs
examples/optional_command.rs
examples/verbose_multiple.rs
src/dopt.rs
src/lib.rs
src/parse.rs
src/synonym.rs
src/test/mod.rs
src/wordlist.rs

This is a breaking change.
* decode() is renamed to deserialize()
for consistency with serde
* docopt_macros is updated to latest nightly
Fixes #128, #213

Migrate from rustc-serialize to serde 1.0

---

README.md
docopt_macros/examples/rustc.rs

I didn't manage to simplify examples/optional_command.rs the same way
(using <&str as Deserialize<'de>>::deserialize(d)),
because of runtime error on this example:
```
invalid type: string "A", expected a borrowed string 
```

Simplify rustc example, update version in README.md

---

src/parse.rs
src/test/mod.rs

fixes #219 by removing `normalize` added in [#200](https://github.com/docopt/docopt.rs/pull/200/files#diff-258c0555e6f9c4bc4fba3a551d81638aR763)
cc: @anka-213

removed repeat normalize, fixed #219

---

README.md

Otherwise, when copying the example as it is from README.md the following weird error occures
```
$ cargo run
Compiling test v0.1.0 (file:///home/.../test)
error[E0463]: can't find crate for `_serde`
--> src/main.rs:26:17
|
26 | #[derive(Debug, Deserialize)]
|                 ^^^^^^^^^^^ can't find crate
error: aborting due to previous error
```

Add serde as dependency in README.md

---

src/dopt.rs

The deserializer in Docopt currently does not support deserializing to types that borrow strings/bytes, resulting in error messages like [this](https://github.com/serde-rs/serde/issues/987).
This PR proposes a change to the type bounds of the couple of `deserialize` functions so that only types that do not borrow data can be deserialized. 
This will break existing code that try to deserialize to structs that borrow data (like the example below), but these code would never have run anyway. Existing code that deserializes to types that do not try to borrow data should not break.
Consider the following example:
```rust
#[macro_use]
extern crate serde_derive;
extern crate docopt;
use docopt::Docopt;
const USAGE: &'static str = "
Simple borrowing
Usage:
borrow <name>
Options:
-h --help …
```

Fix `deserialize` type bounds

---

Cargo.toml

This bumps the minimal acceptable versions in Cargo.toml to versions that are compatible with `-Z minimal-versions`. This is part of the process of seeing how hard this is for crates to use in preparation for getting it stabilized for use in CI, specifically upstreaming the changes required to get criterion working with it. It is easy to use if all of your dependencies support it, but much harder if trying to impose it on them.
cc @BurntSushi follow up to our discussion at https://github.com/rust-lang/regex/pull/504

update regex deb for minimal-versions

---

.travis.yml

This starts work on the [request ](https://github.com/docopt/docopt.rs/pull/241#issuecomment-415872014) to add minimal-versions to CI.
This tests all configuration with `minimal-versions` which is a very aggressive testing resheam. But is a place to start the conversation, and seemed to be easy to do with the way travis is set up.

add minimal-versions to CI
